# Generated by Django 5.0 on 2024-01-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.IntegerField(primary_key=True, serialize=False)),
                ("patient_name", models.CharField(max_length=300)),
                ("patient_age", models.IntegerField()),
                ("patietn_city", models.CharField(max_length=200)),
                ("patient_phone", models.CharField(max_length=10)),
                ("patient_email", models.EmailField(max_length=255)),
                ("patient_gender", models.CharField(max_length=10)),
                ("patient_symptoms", models.CharField(max_length=2000)),
            ],
        ),
    ]
