# Generated by Django 5.0 on 2024-01-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_alter_patient_patient_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_image",
            field=models.ImageField(null=True, upload_to="patient_images/"),
        ),
    ]
