# Generated by Django 5.0 on 2024-01-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_patient_patient_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.AutoField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=300)),
                ("emp_designation", models.CharField(max_length=10)),
                ("emp_email", models.EmailField(max_length=200)),
                ("emp_password", models.CharField(max_length=3000)),
            ],
        ),
    ]
